// Mock data for CAgpt chat application

export const mockChatHistory = [
  {
    id: '1',
    title: 'Corporate Tax Calculation',
    preview: 'How to calculate corporate tax for FY 2023-24?',
    timestamp: '2024-01-15T10:30:00Z',
    subject: 'Taxation'
  },
  {
    id: '2', 
    title: 'Audit Standards',
    preview: 'What are the key audit standards under SA 700?',
    timestamp: '2024-01-14T15:45:00Z',
    subject: 'Audit'
  },
  {
    id: '3',
    title: 'Depreciation Methods',
    preview: 'Difference between SLM and WDV methods?',
    timestamp: '2024-01-13T09:20:00Z',
    subject: 'Accounting'
  },
  {
    id: '4',
    title: 'Companies Act 2013',
    preview: 'Section 149 provisions for independent directors',
    timestamp: '2024-01-12T14:10:00Z',
    subject: 'Law'
  },
  {
    id: '5',
    title: 'GST Returns Filing',
    preview: 'Due dates for GSTR-1 and GSTR-3B returns',
    timestamp: '2024-01-11T11:55:00Z',
    subject: 'Taxation'
  }
];

export const mockMessages = [
  {
    id: '1',
    type: 'user',
    content: 'What are the key provisions of Section 44AD?',
    timestamp: '2024-01-15T10:30:00Z'
  },
  {
    id: '2',
    type: 'bot',
    content: 'Section 44AD is a presumptive taxation scheme for small businesses. Here are the key provisions:\n\n1. **Eligibility**: Available for businesses with turnover up to ₹2 crores\n2. **Presumptive Income**: 8% of gross receipts (6% for digital payments)\n3. **No Book Maintenance**: Detailed books of accounts not required\n4. **Tax Audit**: Not applicable if income declared as per presumptive rate\n5. **Advance Tax**: Only 4 installments required instead of regular due dates\n\nThis scheme simplifies compliance for small taxpayers and reduces their compliance burden.',
    timestamp: '2024-01-15T10:30:15Z'
  },
  {
    id: '3',
    type: 'user', 
    content: 'Can a professional like CA opt for this scheme?',
    timestamp: '2024-01-15T10:32:00Z'
  },
  {
    id: '4',
    type: 'bot',
    content: 'No, professionals like Chartered Accountants cannot opt for Section 44AD. Here\'s why:\n\n1. **Section 44AD** is only for business income, not professional income\n2. **For professionals**, there\'s a separate scheme under **Section 44ADA**\n3. **Section 44ADA provisions**:\n   - Available for professionals with gross receipts up to ₹50 lakhs\n   - Presumptive income rate: 50% of gross receipts\n   - Similar benefits like no book maintenance requirement\n\nSo CAs, doctors, lawyers, architects, etc. should look at Section 44ADA instead of 44AD.',
    timestamp: '2024-01-15T10:32:25Z'
  }
];

export const subjectFilters = [
  'All Subjects',
  'Taxation', 
  'Accounting',
  'Audit',
  'Law',
  'Financial Management',
  'Cost Accounting',
  'Information Technology'
];

export const mockBotResponse = (userMessage) => {
  // Simulate API response delay
  return new Promise((resolve) => {
    setTimeout(() => {
      const responses = [
        'Based on the Indian CA syllabus, here\'s a comprehensive answer to your question...',
        'According to the latest amendments in the Companies Act 2013...',
        'As per the Income Tax Act provisions...',
        'The Accounting Standards (AS) and Indian Accounting Standards (Ind AS) specify...',
        'From an audit perspective, the Standards on Auditing (SA) require...'
      ];
      
      const randomResponse = responses[Math.floor(Math.random() * responses.length)];
      resolve({
        id: Date.now().toString(),
        type: 'bot',
        content: `${randomResponse}\n\nYour query: "${userMessage}"\n\nThis is a mock response. The actual response will be generated by the AI model based on the CA syllabus PDFs.`,
        timestamp: new Date().toISOString()
      });
    }, 1500);
  });
};